# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, fetchgit, HUnit, QuickCheck, testFramework
, testFrameworkHunit, testFrameworkQuickcheck2
}:

cabal.mkDerivation (self: {
  pname = "RFC1751";
  version = "0.3.0.0";
  src = fetchgit {
    url = "git://github.com/np/RFC1751.git";
    sha256 = "bca0caaa073d1a0d828b08632838f414d3358db90e7f4d43045a028540f25327";
    rev = "cb6b960262ce1a7f598a3d08d00a2c348dfed91e";
  };
  buildDepends = [ binary ];
  testDepends = [
    binary HUnit QuickCheck testFramework testFrameworkHunit
    testFrameworkQuickcheck2
  ];
  meta = {
    homepage = "https://github.com/xenog/RFC1751";
    description = "RFC-1751 library for Haskell";
    license = self.stdenv.lib.licenses.publicDomain;
    platforms = self.ghc.meta.platforms;
  };
})
