# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, attoparsec, base16Bytestring, binary, cryptohash
, either, hashable, haskoin, RFC1751, scientific, text
, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "hx";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    aeson attoparsec base16Bytestring binary cryptohash either hashable
    haskoin RFC1751 scientific text unorderedContainers
  ];
  meta = {
    homepage = "https://github.com/np/hx";
    description = "Bitcoin CLI tools: Haskell port of Sx using Haskoin";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
