#!/bin/bash

testname=sha256pbkdf2-pass0word-sa0lt-4096-16.t
command=hx
args=( sha256pbkdf2 - --hex 7361006c74 4096 16 )
exit_code=0
stdin_file=stdin
stdout_file=stdout
stderr_file=/dev/null
sources=( )
products=( )

# Environment variables:
env_vars=( )

setup(){
  : Perform here actions to be run before the tested program
}

munge(){
  : Munge here the results of the tested program to ease the check
}

check(){
  check_exit_code &&
  check_stderr &&
  check_stdout &&
  check_products &&
  : Perform here extra checks on the tested program
}

explain(){
  explain_exit_code
  explain_stdout
  explain_stderr
  explain_products
  : Explain here more potential differences
}

teardown(){
  : Undo here the actions of setup
}
