#!/bin/bash

testname=chksum32-decode-3-parts.t
command=hx
args=( chksum32-decode 80 c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a - )
exit_code=0
stdin_file=stdin
stdout_file=stdout
stderr_file=/dev/null
sources=( )
products=( )

# Environment variables:
env_vars=( )

setup(){
  : Perform here actions to be run before the tested program
}

munge(){
  : Munge here the results of the tested program to ease the check
}

check(){
  check_exit_code &&
  check_stderr &&
  check_stdout &&
  check_products &&
  : Perform here extra checks on the tested program
}

explain(){
  explain_exit_code
  explain_stdout
  explain_stderr
  explain_products
  : Explain here more potential differences
}

teardown(){
  : Undo here the actions of setup
}
