#!/bin/bash

testname=hmac-sha384-test-vector-7.t
command=hx
args=( hmac-sha384 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 5468697320697320612074657374207573696e672061206c6172676572207468616e20626c6f636b2d73697a65206b657920616e642061206c6172676572207468616e20626c6f636b2d73697a6520646174612e20546865206b6579206e6565647320746f20626520686173686564206265666f7265206265696e6720757365642062792074686520484d414320616c676f726974686d2e )
exit_code=0
stdin_file=/dev/null
stdout_file=stdout
stderr_file=/dev/null
sources=( )
products=( )

# Environment variables:
env_vars=( )

setup(){
  : Perform here actions to be run before the tested program
}

munge(){
  : Munge here the results of the tested program to ease the check
}

check(){
  check_exit_code &&
  check_stderr &&
  check_stdout &&
  check_products &&
  : Perform here extra checks on the tested program
}

explain(){
  explain_exit_code
  explain_stdout
  explain_stderr
  explain_products
  : Explain here more potential differences
}

teardown(){
  : Undo here the actions of setup
}
