#!/bin/bash

testname=verifysig-modn-sha256-test-wrong-pub.t
command=hx
args=( verifysig-modn 72155939486846849509759369733266486982821795810448245423168957390607644363272 04cc9519ba6fb1cb0cca53743dc90c2418440cf637f8b891ce2f0e2dc5c5b3cf0138af07d191974089c03e0ca56568f35ee1875e464c6737670025d4512dc8aa17 - )
exit_code=0
stdin_file=stdin
stdout_file=stdout
stderr_file=/dev/null
sources=( )
products=( )

# Environment variables:
env_vars=( )

setup(){
  : Perform here actions to be run before the tested program
}

munge(){
  : Munge here the results of the tested program to ease the check
}

check(){
  check_exit_code &&
  check_stderr &&
  check_stdout &&
  check_products &&
  : Perform here extra checks on the tested program
}

explain(){
  explain_exit_code
  explain_stdout
  explain_stderr
  explain_products
  : Explain here more potential differences
}

teardown(){
  : Undo here the actions of setup
}
