#!/bin/bash

testname=hash160-arg.t
command=hx
args=( hash160 0378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71 )
exit_code=0
stdin_file=/dev/null
stdout_file=stdout
stderr_file=/dev/null
sources=( )
products=( )

# Environment variables:
env_vars=( )

setup(){
  : Perform here actions to be run before the tested program
}

munge(){
  : Munge here the results of the tested program to ease the check
}

check(){
  check_exit_code &&
  check_stderr &&
  check_stdout &&
  check_products &&
  : Perform here extra checks on the tested program
}

explain(){
  explain_exit_code
  explain_stdout
  explain_stderr
  explain_products
  : Explain here more potential differences
}

teardown(){
  : Undo here the actions of setup
}
